#!/usr/bin/env bash

# EXA
alias ls="exa"                                                         # ls
alias ll='exa -lbF --git'                                              # list, size, type, git
alias llm='exa -lbGd --git --sort=modified'                            # long list, modified date sort
alias la='exa -lbhHigUmuSa --time-style=long-iso --git --color-scale'  # all list
alias lx='exa -lbhHigUmuSa@ --time-style=long-iso --git --color-scale' # all + extended list
alias lS='exa -1'                                                      # one column, just names
alias lt='exa --tree --level=2'                                        # tree

# nvim
alias vim="nvim"

# Moving around
alias super="cd ~/Projects/supervisor_app/"
alias dotfiles="cd ~/.config/"
